service:
 name: orders-api

plugins:
 - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1

functions:
  index: 
    handler: dist/index.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any